/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package io.engineeringwithalex.app;

import java.net.*;
import java.io.*;

public class App {

    private void send(String url) throws Exception {
        URL site = new URL(url);
        URLConnection sc = site.openConnection();
        BufferedReader in = new BufferedReader(
                                new InputStreamReader(
                                sc.getInputStream()));
        String inputLine;

        while ((inputLine = in.readLine()) != null) 
            System.out.println(inputLine);
        in.close();
    }

    public String getGreeting() {
        return "Hello, World";
    }

    public static void main(String[] args) throws InterruptedException {
        App app = new App();
        String url = "http://localhost:8000";
        while (true) {
            try {
                app.send(url);
            } catch (Exception e) {
                System.out.println("Error Occurred...");
                e.printStackTrace();
            } finally {
                Thread.sleep(2_000);
            }
        }
    }
}
